#!/bin/bash

#
# LUKS Full disk encryption post-install script
#   based on Debian Buster
#


echo -e "\n----- Update and upgrade system, please wait ... -----\n"

export LANG="en_US.UTF-8"
export LC_ALL="C"

#create lock dir for aptitude
mkdir -p /run/lock
chmod a+rwxt /run/lock

aptitude update >/dev/null
#aptitude -y safe-upgrade # done later

echo -e "\n----------------- Make sure we have the same packages as the standard install ------------------\n"

aptitude -y install acl acpid apt-transport-https at bzip2 cloud-init cloud-initramfs-growroot cloud-utils dbus eatmydata ethtool file gdbm-l10n gettext-base groff-base hdparm htop liblockfile-bin libnss-systemd libpam-systemd locales-all lsof manpages mime-support mtr-tiny ncurses-term netcat-traditional openssh-client openssl patch python python-apt python-minimal python2.7 python3-reportbug qemu-guest-agent reportbug shim-signed sudo traceroute ucf xz-utils
dpkg -P --force-depends amd64-microcode apparmor cpufrequtils discover eject firmware-bnx2x firmware-realtek geoip-database gnupg haveged installation-report intel-microcode iputils-clockdiff iputils-tracepath irqbalance laptop-detect ntpdate pciutils perl rename sgml-base shared-mime-info usb.ids usbutils vim xdg-user-dirs xml-core
aptitude -y -o Aptitude::Delete-Unused=1 purge
aptitude -y safe-upgrade
curl https://packages.hetzner.com/hcloud/deb/hc-utils_0.0.2-1_all.deb -o /tmp/hc-utils_0.0.2-1_all.deb -s
apt install -y -f /tmp/hc-utils_0.0.2-1_all.deb

echo -e "\n----------------- Installing the packages and configuration required for FDE -------------------\n"

echo "cryptroot /dev/sda2 none luks" > /etc/crypttab
mkdir -p /etc/dropbear-initramfs
cat /root/.ssh/authorized_keys >> /etc/dropbear-initramfs/authorized_keys
aptitude -y install dropbear-initramfs
sed -Ei 's/^.?BUSYBOX=.*/BUSYBOX=y/' /etc/initramfs-tools/initramfs.conf
sed -Ei 's/^.?DROPBEAR_OPTIONS=.*/DROPBEAR_OPTIONS="-s -j -k -p 65222 -c \/bin\/cryptroot-unlock"/' /etc/dropbear-initramfs/config
update-initramfs -u
