#!/bin/bash

#
# LUKS Full disk encryption post-install script
#   based on Debian Buster
#


echo -e "\n----- Update and upgrade system, please wait ... -----\n"

export LANG="en_US.UTF-8"
export LC_ALL="C"

#create lock dir for aptitude
mkdir -p /run/lock
chmod a+rwxt /run/lock

aptitude update >/dev/null
aptitude -y safe-upgrade

echo -e "\n----------------- Installing the packages required for FDE ------------------\n"

echo "cryptroot /dev/sda2 none luks" > /etc/crypttab
mkdir -p /etc/dropbear-initramfs
cat /root/.ssh/authorized_keys >> /etc/dropbear-initramfs/authorized_keys
aptitude -y install dropbear-initramfs
sed -i 's/^.?BUSYBOX=.*/BUSYBOX=y/' /etc/initramfs-tools/initramfs.conf
sed -i 's/^.?DROPBEAR_OPTIONS=.*/DROPBEAR_OPTIONS="-s -j -k -p 65222"/' /etc/dropbear-initramfs/config
update-initramfs -u
